port: /dev/ttyDynamixel485
baud_rate: 115200
protocol_version: 2.0

dxl:
  
  protocol_version: 2.0
  number_of_dxl: 7
  
  dxl_ids: [1, 2, 3, 4, 5, 6, 21]
  dxl_names: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "hand_joint"]
  dxl_models: ["xm540_w270", "xm540_w270", "xm540_w270", "xm540_w270", "xm540_w150", "xm540_w150", "xm430_w350"]
  
  dxl_params:
    profile_velocity:
      [1000, 1000, 1000, 1000, 1000, 1000, 1000] # [joint1, joint2, joint3, joint4, joint5, joint6, hand_joint]
    profile_acceleration:
      [2000, 2000, 2000, 2000, 2000, 2000, 2000] # [joint1, joint2, joint3, joint4, joint5, joint6, hand_joint]
        
  limits:
    hard:
      position:
        min: [1024, 513, 683, 348, 1024, 1024, 1024] # [ -90, -135, -120, -150, -90, -90, -90 (Hand) ]
        max: [3072, 3583, 3413, 3748, 3072, 3072, 2320] # [ +90, +135, +120, +150, +90, +90, +20 (Hand) ]
    soft:
      position:
        min: [1024, 513, 683, 348, 1024, 1024, 1024] # [ -90, -135, -120, -150, -90, -90, -90 (Hand) ]
        max: [3072, 3583, 3413, 3748, 3072, 3072, 2320] # [ +90, +135, +120, +150, +90, +90, +20 (Hand) ]

mighty:
  number_of_mighty: 3
  mighty_ids: [1, 2, 3]
  mighty_names: ["gripper_joint1", "gripper_joint2", "gripper_joint3"]
  mighty_models: ["mightyzap_d12_12f_3", "mightyzap_d12_12f_3", "mightyzap_d12_12f_3"]

  limits:
    hard:
      position:
        # max: [1048, 920, 920]
        min: [131, 131, 131]
        max: [2000, 920, 920] 
    soft:
      position:
        # max: [1048, 920, 920]
        min: [131, 131, 131]
        max: [2000, 920, 920]